# start up commands
after-login-command = []
after-startup-command = []
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 0

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = true

# Notify Sketchybar about workspace change and update icons
exec-on-workspace-change = ['/bin/bash', '-c', 'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE PREV_WORKSPACE=$AEROSPACE_PREV_WORKSPACE && ~/.config/sketchybar/plugins/update_workspace_icons.sh']
#############################################################
#############################################################
#############################################################
#############################################################
#############################################################
#############################################################
[gaps]
    inner.horizontal = 5
    inner.vertical =   5
    outer.left =       0
    outer.right =      0
    outer.bottom =     0
#  outer.top = [{ monitor."main" = 4 }, 35] # solo big display
  outer.top = [{ monitor."main" = 35}, 35] # mac 10, display 35
#############################################################
#############################################################
#############################################################
#############################################################
#############################################################
#############################################################
#############################################################
#############################################################
[key-mapping]
    preset = 'qwerty'

[mode.main.binding]
    ctrl-h = 'focus left'
    ctrl-j = 'focus down'
    ctrl-k = 'focus up'
    ctrl-l = 'focus right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    # Swap commands
    cmd-shift-quote = ['swap right']
    cmd-shift-semicolon = ['swap left']

    # Change orientation shortcuts
    alt-shift-1 = 'layout vertical horizontal'
    alt-shift-2 = 'layout horizontal vertical'


    # Resize commands
    cmd-shift-leftSquareBracket = 'resize smart +150'  # make left-most tile bigger
    cmd-shift-rightSquareBracket = 'resize smart -150'  # make right-most tile bigger

    # Workspace commands
    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace
    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    # Move node to workspace and switch
    # See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
    cmd-shift-1 = ['move-node-to-workspace 1']
    cmd-shift-2 = ['move-node-to-workspace 2']
    cmd-shift-3 = ['move-node-to-workspace 3']
    cmd-shift-4 = ['move-node-to-workspace 4']
    cmd-shift-5 = ['move-node-to-workspace 5']
    cmd-shift-6 = ['move-node-to-workspace 6']
    cmd-shift-7 = ['move-node-to-workspace 7']

    # Workspace navigation
    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
    alt-tab = 'workspace-back-and-forth'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    # Switch to service mode
    # See: https://nikitabobko.github.io/AeroSpace/commands#mode
    alt-shift-semicolon = 'mode service'

    # Service binding mode
    # See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main']
    f = ['layout floating tiling', 'mode main']
    backspace = ['close-all-windows-but-current', 'mode main']
    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']
    alt-shift-r = ['exec-and-forget /opt/homebrew/bin/sketchybar --reload']

# Default space
[[on-window-detected]]
if.app-id ='com.arc.Browser'
run = ['move-node-to-workspace 1']

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = ['move-node-to-workspace 1']

[[on-window-detected]]
if.app-id ='md.obsidian'
run = ['move-node-to-workspace 2']

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'
run = ['move-node-to-workspace 3']

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = ['move-node-to-workspace 3']

[[on-window-detected]]
if.app-id = 'us.zoom.xos'
run = ['move-node-to-workspace 3']

[[on-window-detected]]
if.app-id = 'com.microsoft.Powerpoint'
run = ['move-node-to-workspace 4']

[[on-window-detected]]
if.app-id = 'com.microsoft.Word'
run = ['move-node-to-workspace 4']

[[on-window-detected]]
if.app-id = 'org.zotero.Zotero'
run = ['move-node-to-workspace 4']

[[on-window-detected]]
if.app-id = 'com.apple.Preview'
run = ['move-node-to-workspace 4']

[[on-window-detected]]
if.app-id = 'com.apple.iCal'
run = ['move-node-to-workspace 5']
